Prueba002/Prueba002/Prueba002/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba002.Models;
using System.Diagnostics;

namespace Prueba002.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Procesadores()
        {
            return View();
        }

		public IActionResult TarjetasGraficas()
		{
			return View();
		}

		public IActionResult PlacaMadre()
		{
			return View();
		}

		public IActionResult MemoriasRAM()
		{
			return View();
		}

		public IActionResult FuentesDePoder()
		{
			return View();
		}

		public IActionResult Disipadores()
		{
			return View();
		}

		public IActionResult Almacenamiento()
		{
			return View();
		}

		public IActionResult Index()
        {
            return View();
        }

		public IActionResult Gabinetes()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prueba002/Prueba002/Prueba002/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba002.Models.dbModels;

namespace Prueba002.Controllers
{
    
    public class ProductosController : Controller
    {
        private readonly Incio_ProyectoContext _context;

        public ProductosController(Incio_ProyectoContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            var incio_ProyectoContext = _context.Productos.Include(p => p.IdCategoriaNavigation).Include(p => p.IdMarcasNavigation);
            return View(await incio_ProyectoContext.ToListAsync());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.IdCategoriaNavigation)
                .Include(p => p.IdMarcasNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }
        [Authorize(Roles = "Administrador")]

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarcas"] = new SelectList(_context.Marcas, "IdMarcas", "Marcas");
            return View();
        }
        [Authorize(Roles = "Administrador")]
        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducto,NombreProducto,Descripcion,IdCategoria,Stock,PrecioProducto,IdMarcas")] Models.ProductoHR producto)
        {
            if (ModelState.IsValid)
            {
                Producto producto1 = new Producto
                {
                    NombreProducto = producto.NombreProducto,
                    Descripcion = producto.Descripcion,
                    IdCategoria=producto.IdCategoria,
                    Stock=producto.Stock,
                    PrecioProducto=producto.PrecioProducto,
                    IdMarcas=producto.IdMarcas,
                };
                _context.Productos.Add(producto1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarcas"] = new SelectList(_context.Marcas, "IdMarcas", "Marcas");
            return View(producto);
        }
        [Authorize(Roles = "Administrador")]
        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarcas"] = new SelectList(_context.Marcas, "IdMarcas", "Marcas");
            return View(producto);
        }
        [Authorize(Roles = "Administrador")]
        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProducto,NombreProducto,Descripcion,IdCategoria,Stock,PrecioProducto,IdMarcas")] Models.ProductoHR producto)
        {
            if (id != producto.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Producto producto1 = new Producto
                {
                    NombreProducto = producto.NombreProducto,
                    Descripcion = producto.Descripcion,
                    IdCategoria = producto.IdCategoria,
                    Stock = producto.Stock,
                    PrecioProducto = producto.PrecioProducto,
                    IdMarcas = producto.IdMarcas,
                };
                
                try
                {
                    _context.Productos.Update(producto1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarcas"] = new SelectList(_context.Marcas, "IdMarcas", "Marcas");
            return View(producto);
        }
        [Authorize(Roles = "Administrador")]
        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.IdCategoriaNavigation)
                .Include(p => p.IdMarcasNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }
        [Authorize(Roles = "Administrador")]
        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity set 'Incio_ProyectoContext.Productos'  is null.");
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto != null)
            {
                _context.Productos.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Productos?.Any(e => e.IdProducto == id)).GetValueOrDefault();
        }
    }
}

Prueba002/Prueba002/Prueba002/Views/Home/Almacenamiento.cshtml
@{
	ViewData["Title"] = "Almacenamiento";
}
<header>
	<h1>Almacenamiento</h1>
	<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</header>

<script>
    $(document).ready(function () {
        // Obtén el ID de categoría deseado (en este caso, 12)
        var categoryIdToFilter = 12;

        // Oculta las filas que no cumplen con el criterio de la categoría
        $('tbody tr').each(function () {
            var categoryId = parseInt($(this).find('td:eq(4)').text()); // Índice 4 es la columna de IdCategoriaNavigation

            if (categoryId !== categoryIdToFilter) {
                $(this).hide();
            }
        });

        // Puedes agregar un botón u otro evento para restablecer el filtro si es necesario
        $('#resetFilter').click(function () {
            $('tbody tr').show();
        });
    });
</script>

Prueba002/Prueba002/Prueba002/Views/Home/Disipadores.cshtml
@{
	ViewData["Title"] = "Disipadores";
}
<header>
	<h1>Disipadores</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/FEFA.cshtml
@{
    ViewData["Title"] = "FEFA";
}
<h1>Mi presentacion personal</h1>
<p>
    Soy un estudiante de la facultad de Ingenieria Mecanica y Electrica (FIME) estudie en la
    preparatoria Industrial Pablo LIvas unidad poniente y algunos de los logros
    de mis estudios son algunas certificaciones con las que cuento sobre office y un titulo de tecnico mecanico automottriz
    me motiva el deseo de seguir adelante y en algun punto ayudar a mi familia.
</p>
<h2>Formacion academica</h2>
<ol>
    <li>Facultad de Ingenieria Mecanica y Electrica (FIME) cursando.</li>
    <li>Escuela Industrial y Preparatoria Tecnica Pablo Livas como tecnico en sistemas computacionales.</li>
    <li>Secundaria Técnica 96 Gonzalo Aguirre Beltrán como tecnico mecanico automotriz.</li>
</ol>
<h2>Mis pasatiempos.</h2>
<ul>
    <li>Videjuegos.</li>
    <li>Tecnologia.</li>
    <li>Mecanica automotriz.</li>
    <li>Configuracion, mantenimiento y reparacion de equipos de computo.</li>
</ul>
<h2>Fotografia de presentacion</h2>

Prueba002/Prueba002/Prueba002/Views/Home/FuentesDePoder.cshtml
@{
	ViewData["Title"] = "FuentesDePoder";
}
<header>
	<h1>Fuentes de Poder</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/Gabinetes.cshtml
@{
	ViewData["Title"] = "Gabinetes";
}
<header>
	<h1>Gabinetes</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <header class="header-index">
        <div class="">
            <h1 class="">¡Bienvenidos a TecnoByte!</h1>
            <h1 class="">¿Qué Desea Comprar Hoy?</h1>
        </div>
        
        <div class="iconos-index">
        <!-- Carrito Button -->
        <button class="cart-button" onclick="window.location.href='/Carritos/Index'">
            Carrito
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 inline-block ml-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 4L2 6m0 0L1 7m1-1L2 6m7 13h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v4m0 6h10a2 2 0 002-2v-2H5a2 2 0 002 2z" />
            </svg>
        </button>

        <!-- Compra Button -->
        <button class="purchase-button" onclick="window.location.href='/Compras/Index'">
            Compra
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 inline-block ml-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 4l2 16h12l2-16M7 4h10" />
            </svg>
        </button>
        </div>
    </header>

    <div class="container-items">
        <div class="row">
            <!--Procesadores-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/Procesadores.jpg" alt="Procesadores" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Procesadores</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=12" >Ir a Procesadores</a></button>
                    </div>
                </div>
            </div>

            <!--Tarjetas Graficas-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/TarjetasGraficas.jpg" alt="Tarjeta Grafica" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Tarjetas Graficas</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=13">Ir a Tarjetas Graficas</a></button>
                    </div>
                </div>
            </div>

            <!--Placa Madre-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/PlacaMadre.png" alt="Placa Madre" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Placa Madre</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=14">Ir a Placas Madre</a></button>
                    </div>
                </div>
            </div>

            <!--Almacenamiento-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/SSD NVMe.png" alt="Almacenamiento" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Almacenamiento</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=15">Ir a Almacenamiento</a></button>
                    </div>
                </div>
            </div>

            <!--Gabinetes-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/Gabinetes.jpg" alt="Gabinetes" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Gabinetes</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=16">Ir a Gabinetes</a></button>
                    </div>
                </div>
            </div>

            <!--Disipadores-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/Disipadores.png" alt="Disipadores" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Disipadores</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=19">Ir a Disipadores</a></button>
                    </div>
                </div>
            </div>

            <!--Fuentes De Poder-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/FuenteDePoder.jpg" alt="Fuentes De Poder" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Fuentes de Poder</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=17">Ir a Fuentes De Poder</a></button>
                    </div>
                </div>
            </div>

            <!--Memoras RAM-->
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="item">
                    <figure>
                        <img src="~/Imagenes/MemoriaRAM.jpeg" alt="Memorias Ram" />
                    </figure>
                    <div class="Info-Producto">
                        <h2>Memorias RAM</h2>
                    <button><a asp-controller="Productos" asp-action="Index" asp-route-id="id=18">Ir a Memorias RAM</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Prueba002/Prueba002/Prueba002/Views/Home/MemoriasRAM.cshtml
@{
	ViewData["Title"] = "MemoriasRAM";
}
<header>
	<h1>Memorias RAM</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/PlacaMadre.cshtml
@{
	ViewData["Title"] = "PlacaMadre";
}
<header>
	<h1>Placas Madre</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/Procesadores.cshtml
@{
    ViewData["Title"] = "Procesadores";
}

<header>
    <h1>Procesadores</h1>
</header>

Prueba002/Prueba002/Prueba002/Views/Home/TarjetasGraficas.cshtml
@{
	ViewData["Title"] = "TarjetasGraficas";
}

<header>
	<h1>Tarjetas Graficas</h1>
</header>